version: "3.9"

services:
  app:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - db_sqlite:/app/db.sqlite3
    command: gunicorn interview_tg_bot.wsgi:application --bind 0.0.0.0:8000 && python main.py
    expose:
      - 8000
    env_file:
      - ./.env

  bot:
    build: .
    command: python main.py
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app


volumes:
  static_volume: