# Generated by Django 4.2.2 on 2023-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.TextField(),
        ),
    ]
